version: "3"
services:
    main:
        build:
          context: .
        networks:
          - usb_nw0

        tty: true
        stdin_open: true

    test:
        build: ./docker/test_container
        networks:
          - usb_nw0

networks:
  usb_nw0:
    name: usb_nw0
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.1.0/24
  usb_nw1:
    name: usb_nw1
    ipam:
      config:
        - subnet: 172.21.0.0/16
          ip_range: 172.21.1.0/24
  en0:
    name: en0
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.1.0/24
